version: "3.8"

services:

  # web:
  #   restart: always
  #   container_name: web_peelJobs
  #   build:
  #     context: .
  #   command: python3 manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  #     - pgdb

  pgdb:
    container_name: pgdb_peeljob
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_DATABASE: mongo1
    #   MONGO_INITDB_ROOT_USERNAME: mongo1
    #   MONGO_INITDB_ROOT_PASSWORD: mongo1
    volumes:
      - ./db-data/mongo/:/data/db

  elasticsearch:
    container_name: elasticsearch_peeljob
    image: elasticsearch:7.14.2
    environment:
      - cluster.name=jobsp-elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - "9200:9200"
    depends_on:
      - pgdb

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  # memcached:
  #   container_name: some-memcached
  #   image: launcher.gcr.io/google/memcached1
  #   ports:
  #     - '11211:11211'

  celery:
    container_name: celery_peel
    restart: always
    build:
      context: .
    command: celery -A jobsp worker -l info
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379:0
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app/

  celery-beat:
    container_name: celery_beat_peel
    restart: always
    build:
      context: .
    command: celery -A jobsp beat -l info
    depends_on:
      - redis
      - celery
    volumes:
      - .:/usr/src/app/

  flower:
    container_name: flower_peel
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
