from django.urls import path, include, re_path
from recruiter.views import (index, getout, registration_success, how_it_works, verify_mobile,
                             send_mobile_verification_code, account_activation,
                             user_profile, change_password, jobs_list, inactive_jobs,
                             new_job, edit_job, view_job, preview_job, copy_job,
                             deactivate_job, enable_job, delete_job, resume_upload,
                             applicants, view_company, multiple_resume_upload,
                             enable_email_notifications, edit_company, company_recruiter_list,
                             company_recruiter_create, edit_company_recruiter, resume_pool,
                             delete_company_recruiter, activate_company_recruiter,
                             company_recruiter_profile, resume_view, resume_edit)
from .views import (dashboard, hired_candidates,
                    jobs_billing_process, client_list, add_client, edit_client,
                    delete_client, client_profile, add_branch, add_contract_deatils,
                    applicant_status_change, user_work_log,
                    delete_applicant_status, delete_resume, view_resumes,
                    job_status_change)

app_name = "agency"

urlpatterns = [

    re_path(r'^$', index, name="index"),
    re_path(r'^out/$', getout, name="getout"),

    re_path(r'^thank-you-message/$', registration_success,
        name="registration_success"),
    re_path(r'^how-it-works/$', how_it_works, name="how_it_works"),
    re_path(r'^dashboard/$', dashboard, name="dashboard"),

    re_path(r'^mobile/verify/$', verify_mobile, name="verify_mobile"),
    re_path(r'^send/mobile_verification_code/$',
        send_mobile_verification_code, name="send_mobile_verification_code"),
    re_path(r'^activation/(?P<user_id>[a-zA-Z0-9]+)/$',
        account_activation, name="account_activation"),
    re_path(r'^profile/$', user_profile, name="profile"),
    re_path(r'^change-password/$', change_password, name="change_password"),
    re_path(r'^work-log/$', user_work_log, name="user_work_log"),

    re_path(r'^job/list/$', jobs_list, name="list"),
    re_path(r'^job/inactive/list/$', inactive_jobs, name="inactive_jobs"),
    re_path(r'^job/(?P<status>[-\w]+)/new/$', new_job, name="new"),
    re_path(r'^job/edit/(?P<job_post_id>[a-zA-Z0-9]+)/$', edit_job, name="edit"),
    re_path(r'^job/view/(?P<job_post_id>[a-zA-Z0-9]+)/$', view_job, name="view"),
    re_path(r'^job/preview/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        preview_job, name="preview"),
    re_path(r'^job/(?P<status>[-\w]+)/copy/$', copy_job, name="copy"),
    re_path(r'^job/deactivate/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        deactivate_job, name="deactivate_job"),
    re_path(r'^job/enable/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        enable_job, name="enable"),
    re_path(r'^job/delete/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        delete_job, name="delete"),
    re_path(r'^job/applicants/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        applicants, name="applicants"),

    re_path(r'^job/resumes/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        view_resumes, name="view_resumes"),
    re_path(r'^job/status/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        job_status_change, name="job_status_change"),
    re_path(r'^job/enable-email-notifications/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        enable_email_notifications, name="enable_email_notifications"),

    re_path(r'^job/hired-candidates/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        hired_candidates, name="hired_candidates"),

    re_path(r'^job/billing/(?P<job_post_id>[a-zA-Z0-9]+)/$',
        jobs_billing_process, name="jobs_billing_process"),
    re_path(r'^company/edit/$', edit_company, name="edit_company"),

    re_path(r'^recruiters/$', company_recruiter_list,
        name="company_recruiter_list"),
    re_path(r'^recruiter/add/$', company_recruiter_create,
        name="company_recruiter_create"),
    re_path(r'^recruiter/edit/(?P<recruiter_id>[a-zA-Z0-9]+)/$',
        edit_company_recruiter, name="edit_company_recruiter"),
    re_path(r'^recruiter/delete/(?P<recruiter_id>[a-zA-Z0-9]+)/$',
        delete_company_recruiter, name="delete_company_recruiter"),
    re_path(r'^recruiters/status/(?P<recruiter_id>[a-zA-Z0-9]+)/$',
        activate_company_recruiter, name="activate_company_recruiter"),
    re_path(r'^recruiters/profile/(?P<recruiter_id>[a-zA-Z0-9]+)/$',
        company_recruiter_profile, name="company_recruiter_profile"),

    re_path(r'^clients/$', client_list, name="client_list"),
    re_path(r'^clients/add/$', add_client, name="add_client"),
    re_path(r'^clients/edit/(?P<client_id>[a-zA-Z0-9]+)/$',
        edit_client, name="edit_client"),
    re_path(r'^clients/delete/(?P<client_id>[a-zA-Z0-9]+)/$',
        delete_client, name="delete_client"),
    re_path(r'^clients/profile/(?P<client_id>[a-zA-Z0-9]+)/$',
        client_profile, name="client_profile"),

    re_path(r'^clients/branch/(?P<branch_id>[a-zA-Z0-9]+)/$',
        add_branch, name="add_branch"),
    re_path(r'^clients/contract-details/(?P<contact_details_id>[a-zA-Z0-9]+)/$',
        add_contract_deatils, name="add_contract_deatils"),

    re_path(r'^resume/pool/$', resume_pool, name="resume_pool"),
    re_path(r'^resume/upload/$', resume_upload, name="resume_upload"),
    re_path(r'^multiple/resumes/upload/$', multiple_resume_upload, name="multiple_resume_upload"),
    re_path(r'^resume/edit/(?P<resume_id>[a-zA-Z0-9]+)/$',
        resume_edit, name="resume_edit"),
    re_path(r'^resume/view/(?P<resume_id>[a-zA-Z0-9]+)/$',
        resume_view, name="resume_view"),
    re_path(r'^applicant/status/(?P<applicant_id>[a-zA-Z0-9]+)/$',
        applicant_status_change, name="applicant_status_change"),
    re_path(r'^applicant/delete/(?P<applicant_id>[a-zA-Z0-9]+)/$',
        delete_applicant_status, name="delete_applicant_status"),

    re_path(r'^resume/delete/(?P<resume_id>[a-zA-Z0-9]+)/$',
        delete_resume, name="delete_resume"),
    re_path(r'^microsite-page/$', view_company, name="view_company"),

]
