# Generated by Django 4.2 on 2023-04-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import peeldb.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_blog_it", "0005_initial"),
        ("peeldb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "attached_file",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=peeldb.models.img_url,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_blog_it.post",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
