# Generated by Django 4.2 on 2023-04-30 10:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0002_credentialsmodel_solution_question_blogattachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/media/file"
                ),
                upload_to="uploads/",
            ),
        ),
    ]
