# Generated by Django 4.2 on 2023-04-15 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0004_question_assessmentdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialsModel",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("credential", models.BinaryField()),
            ],
        ),
    ]
