# Generated by Django 4.2 on 2023-04-30 12:26

from django.db import migrations, models
import peeldb.models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0005_alter_skill_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=peeldb.models.img_url
            ),
        ),
    ]
