# Generated by Django 4.2 on 2023-04-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0005_credentialsmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
