# Generated by Django 4.2 on 2023-04-30 20:38

from django.db import migrations, models
import peeldb.models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0006_alter_skill_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="campaign_icon",
            field=models.FileField(
                blank=True, max_length=1000, null=True, upload_to=peeldb.models.img_url
            ),
        ),
    ]
