# Generated by Django 4.2 on 2023-05-06 20:57

from django.db import migrations, models
import peeldb.models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0007_alter_company_campaign_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="resume",
            field=models.FileField(
                blank=True, max_length=1000, null=True, upload_to=peeldb.models.img_url
            ),
        ),
    ]
