# Generated by Django 4.2 on 2023-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0008_alter_user_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="resume",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
